# embed_uic.cmake generates a C header embedding a binary file as an
# unsigned char array using only CMake builtins.
#
# Inputs:
#   UIC_FILE     - input wasamoc-emitted .uic file
#   HEADER_FILE  - output C header path
#   ARRAY_NAME   - C identifier for the byte array
#   HEADER_GUARD - include guard identifier

if(NOT DEFINED ARRAY_NAME)
    set(ARRAY_NAME "GALLERY_UIC")
endif()

if(NOT DEFINED HEADER_GUARD)
    set(HEADER_GUARD "WASAMO_GALLERY_UIC_H")
endif()

file(READ "${UIC_FILE}" UIC_HEX HEX)
string(LENGTH "${UIC_HEX}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

string(REGEX REPLACE "(..)" "0x\\1, " UIC_BYTES "${UIC_HEX}")

file(WRITE "${HEADER_FILE}"
"/* Auto-generated by embed_uic.cmake from ${UIC_FILE}. Do not edit. */
#ifndef ${HEADER_GUARD}
#define ${HEADER_GUARD}

#include <stddef.h>

static const unsigned char ${ARRAY_NAME}[] = { ${UIC_BYTES} };
static const size_t ${ARRAY_NAME}_LEN = ${BYTE_LEN};

#endif /* ${HEADER_GUARD} */
")
