# embed_uic.cmake — generate a C header embedding a binary file as
# `unsigned char[]` (xxd -i style) using only CMake builtins.
#
# Inputs (set on cmake -P command line):
#   UIC_FILE     — input binary file (the wasamoc-emitted .uic)
#   HEADER_FILE  — output C header path
#   ARRAY_NAME   — C identifier for the byte array (default: COUNTER_UIC)

if(NOT DEFINED ARRAY_NAME)
    set(ARRAY_NAME "COUNTER_UIC")
endif()

file(READ "${UIC_FILE}" UIC_HEX HEX)
string(LENGTH "${UIC_HEX}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# "ab12..." -> "0xab, 0x12, "
string(REGEX REPLACE "(..)" "0x\\1, " UIC_BYTES "${UIC_HEX}")

file(WRITE "${HEADER_FILE}"
"/* Auto-generated by embed_uic.cmake from ${UIC_FILE}. Do not edit. */
#ifndef WASAMO_COUNTER_UIC_H
#define WASAMO_COUNTER_UIC_H

#include <stddef.h>

static const unsigned char ${ARRAY_NAME}[] = { ${UIC_BYTES} };
static const size_t ${ARRAY_NAME}_LEN = ${BYTE_LEN};

#endif /* WASAMO_COUNTER_UIC_H */
")
